### ISSUE TITLE
Incompatibility with prettier

### ISSUE THREAD

**Issue by unphased** [vanruesc/eslint-config-aether#1]
It looks like prettier is sufficiently opinionated as to be [incompatible](https://github.com/prettier/prettier/issues/2352) with the [padded-blocks rule](http://eslint.org/docs/rules/padded-blocks). 

I have tried to set up `prettier-eslint` flow but the editor setup I'm currently using (vim/nvim with coc.nvim and coc-prettier) is seemingly deeply broken at being able to feed prettier output into eslint --fix. 

Anyway, the immediate workaround is to put an ignore on all files with `.prettierignore`.

**Comment by vanruesc** [comment]
I don't think I understand. Why would you use prettier with an eslint config? This config only works with ESLint. There is no implied compatibility with other lint tools.

**Comment by unphased** [comment]
To be totally honest, I like the way you have things set up. It's minimalist in a way that web development groupthink is sorely lacking these days and is really refreshing. 

The fact that prettier makes it so tricky to disable itself is mostly prettier's fault. 

I'm just noting here for others who have prettier set up globally that the way to not have pain working with this eslint config is to just force prettier off via `*` inside of a `.prettierrc` in the repo.

**Comment by vanruesc** [comment]
I see, thanks for clarifying!
